// ✅ Script UTM complet prêt à héberger sur GitHub

// 1. Configuration globale des UTMs par page
window.PAGE_UTM_CONFIG = {
  '/': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'homepage' },
  '/formation-data-analyst': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'data_analytics_generaliste' },
  '/formation-data-analyst/paris': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'data_analytics_paris' },
  '/formation-data-analyst/a-distance': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'data_analytics_distance' },
  '/formation-data-analyst/champion': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'data_analytics_champion' },
  '/formation-data-analyst/essentials': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'data_analytics_essentials' },
  '/formation-data-scientist': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'data_scientist_generaliste' },
  '/formation-data-scientist/champion': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'data_scientist_champion' },
  '/formation-data-engineer': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'data_engineer_generaliste' },
  '/formation-data-engineer/analytics-engineer-databird-datagen': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'analytics_engineer' },
  '/formation-data-engineer/data-orchestration': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'data_orchestration' },
  '/formation-gen-ai': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'gen_ai' },
  '/formation-ia/agent-ia': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'agent_ia' },
  '/formation-ia/ia-champion': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'ia_champion' },
  '/offre-entreprise': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'offre_entreprise' },
  '/formation/excel': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'outils_excel' },
  '/formation/power-bi': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'outils_powerbi' },
  '/formation/google-sheets': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'outils_google_sheets' },
  '/formation/looker-studio': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'outils_looker_studio' },
  '/formation/python': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'outils_python' },
  '/formation/sql': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'outils_sql' },
  '/formation/tableau-software': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'outils_tableau' },
  '/certification/excel': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'certification_excel' },
  '/certification/power-bi': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'certification_powerbi' },
  '/campus/': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'data_analyst_distance' },
  '/cours-gratuit/': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'cours_gratuit_général' },
  '/cours-gratuit/les-bases-de-sql-a-ta-portee': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'cours_gratuit_sql' },
  '/cours-gratuit/dbt': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'cours_gratuit_dbt' },
  '/cours-gratuit/excel': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'cours_gratuit_excel' },
  '/cours-gratuit/le-jargon-de-la-data': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'cours_gratuit_acculturation_data' },
  '/qui-sommes-nous': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'qui_sommes_nous' },
  '/parrainage': { utm_source: 'website', utm_medium: 'referral', utm_campaign: 'parrainage' },
  '/faq': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'faq' },
  '/offre-promo-ete-2025': { utm_source: 'website', utm_medium: 'organic_search', utm_campaign: 'OP_ete' },
  '/c/google/formation-databird': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/formation-data-analyst-temps-partiel': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/formation-sql-databird': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-excel-certifiante': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/formation-data-analyst-temps-plein': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-paris-v2': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-paris': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/formation-certifiante-power-bi': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-power-bi-certifiante-v2': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-power-bi-certifiante': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/partenariat-malt-x-databird': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-a-distance': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-engineer': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/formation-tableau-software-databird': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-tableau-software': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-sql': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/formation-ia/agent-ia': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/formation-ia/ia-champion': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-toulouse': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-lille': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-lyon': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-nantes': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-nice': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-rennes': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-grenoble': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-marseille': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-montpellier': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-strasbourg': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/google/formation-data-analyst-bordeaux': { utm_source: 'google', utm_medium: 'paid_search', utm_campaign: '' },
  '/c/meta/data-recrutement-quel-marche-en-2024': { utm_source: 'facebook', utm_medium: 'paid_social', utm_campaign: '' },
  '/c/meta/data-analyst-preparer-son-entretien-dembauche': { utm_source: 'facebook', utm_medium: 'paid_social', utm_campaign: '' },
  '/c/meta/salaire-data-analyst': { utm_source: 'facebook', utm_medium: 'paid_social', utm_campaign: '' },
  '/c/meta/montees-en-competences': { utm_source: 'facebook', utm_medium: 'paid_social', utm_campaign: '' },
  '/c/meta/reconversion': { utm_source: 'facebook', utm_medium: 'paid_social', utm_campaign: '' },
  '/c/meta/data-essentials': { utm_source: 'facebook', utm_medium: 'paid_social', utm_campaign: '' },
  '/c/meta/formation-data-analyst': { utm_source: 'facebook', utm_medium: 'paid_social', utm_campaign: '' },
  '/activation/offre-noel-databird-2024': { utm_source: 'facebook', utm_medium: 'paid_social', utm_campaign: '' },
  '/activation/offre-data-ia': { utm_source: '', utm_medium: '', utm_campaign: 'OP_Avril_2025_losts' },
  '/activation/offre-data-ia-alumni-excel': { utm_source: '', utm_medium: '', utm_campaign: 'OP_Avril_2025_alumni_excel' },
  '/activation/offre-data-ia-alumni-dae': { utm_source: '', utm_medium: '', utm_campaign: 'OP_Avril_2025_alumni_dae' },
  '/activation/offre-data-ia-alumni-outils-expert': { utm_source: '', utm_medium: '', utm_campaign: 'OP_Avril_2025_alumni_outils_expert' },
  '/activation/offre-data-ia-alumni-alumni-metiers': { utm_source: '', utm_medium: '', utm_campaign: 'OP_Avril_2025_alumni_alumni_metiers' },
  '/activation/formations-ia': { utm_source: '', utm_medium: '', utm_campaign: 'offre_IA_sept2025' },
  '/c/meta/reconversion-recherche-demploi': { utm_source: 'facebook', utm_medium: 'paid_social', utm_campaign: '' },
  '/c/meta/data-ia-report': { utm_source: 'facebook', utm_medium: 'paid_social', utm_campaign: '' }
};


// 2. Script UTM (version minifiée avec logs)
(function(){const u=["utm_source","utm_medium","utm_campaign","utm_term","utm_content"],d={utm_source:"website",utm_medium:"unknown_page",utm_campaign:"general",utm_content:"cta_formulaire",utm_term:""},c=window.PAGE_UTM_CONFIG||{},p=window.location.pathname,g=(p.startsWith("/campus/")&&p!=="/campus/")?{...d,utm_source:"website",utm_medium:"organic_search",utm_campaign:`data_analyst_distance_${p.split("/").pop()}`,utm_content:"cta_formulaire"}:{...d,...(c[p]||{})},s=t=>{const e={};return u.forEach(k=>{const v=new URLSearchParams(location.search).get(k);v&&(e[k]=v)}),e},l=()=>{const e=JSON.parse(sessionStorage.getItem("initialUtms")||"null"),r=s(),t=g;return Object.keys(r).length>0?(sessionStorage.setItem("initialUtms",JSON.stringify({...t,...r})),{...t,...r}):e||t},f=t=>{if(!t)return;const e=l();console.log("[UTM] Injection dans formulaire:",e);for(const[k,v]of Object.entries(e)){let i=t.querySelector(`input[name="${k}"]`);i||(i=document.createElement("input"),i.type="hidden",i.name=k,t.appendChild(i)),i.value=v}},b=e=>{if(!e)return null;const t=e.querySelector("form");if(t)return t;for(const i of e.querySelectorAll("iframe"))try{const d=i.contentDocument||i.contentWindow?.document,f=d?.querySelector("form");if(f)return f}catch{}return e.querySelector(".hs-form")},m=()=>{const cont=document.querySelector(".meetings-iframe-container");const i=cont?.querySelector("iframe")||document.querySelector(".meetings-iframe-container iframe");if(!cont&&!i)return!1;if(window.__UTM_MEETING_DONE===true)return!1;const base=(cont&&cont.getAttribute("data-src"))||(i&&i.src);if(!base)return!1;const e=l(),r=new URL(base,location.origin);let changed=!1;for(const[k,v]of Object.entries(e)){if(!r.searchParams.has(k)){r.searchParams.set(k,v);changed=!0}}if(!changed){window.__UTM_MEETING_DONE=true;return!1}const final=r.toString();if(cont&&cont.getAttribute("data-src")!==final){cont.setAttribute("data-src",final)}if(i&&i.src!==final){i.src=final}window.__UTM_MEETING_DONE=true;console.log("[UTM] Iframe meetings UTM ajouté une seule fois:",final);return!0},a=()=>{if(m())return;const e=document.querySelector('[data-hubspot-form-container="true"]'),t=b(e);t&&(f(t),t._utmListenerAdded||(t.addEventListener("submit",()=>f(t)),t._utmListenerAdded=!0))};document.readyState!=="loading"?(()=>{a();[1e3,2e3,3e3,5e3].forEach(t=>setTimeout(a,t));const o=new MutationObserver(()=>a());o.observe(document.body,{childList:!0,subtree:!0}),setTimeout(()=>o.disconnect(),3e4)})():document.addEventListener("DOMContentLoaded",()=>{a();[1e3,2e3,3e3,5e3].forEach(t=>setTimeout(a,t));const o=new MutationObserver(()=>a());o.observe(document.body,{childList:!0,subtree:!0}),setTimeout(()=>o.disconnect(),3e4)});})();
